[package]
name = "bed-plugin-font"
version = "0.1.0"
edition = "2024"
publish = false
license-file = "../../LICENSE"

[dependencies]
bed-core = { workspace = true }
bed-plugin = { workspace = true, features = ["gpu"] }
bed-ui = { workspace = true }
dear-imgui-rs = { workspace = true }
dear-imgui-sys = { workspace = true }
serde_json = { workspace = true }
harfrust = { workspace = true }
wuff = { workspace = true }
flate2 = { workspace = true }
