[package]
name = "bed-plugin-json"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
bed-editing = { workspace = true }
bed-plugin = { workspace = true }
dear-imgui-rs = { workspace = true }
jsonc-parser = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
