[package]
name = "bed-files"
version = "0.1.0"
edition = "2024"
publish = false
license-file = "../../LICENSE"

[dependencies]
bed-editing = { workspace = true }
bed-remote = { workspace = true }
git2 = { workspace = true }
regex = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[[test]]
name = "remote_services"
path = "tests/remote_services.rs"
harness = false
