[package]
name = "bed-plugin-csv"
version = "0.1.0"
edition = "2024"
publish = false
license-file = "../../LICENSE"

[dependencies]
bed-ui = { workspace = true }
bed-editing = { workspace = true }
bed-plugin = { workspace = true }
bed-document-session = { workspace = true }
dear-imgui-rs = { workspace = true }
dear-imgui-sys = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
