[package]
name = "bed-lsp"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
bed-editing = { workspace = true }
bed-remote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
