[package]
name = "bed-scenes"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
bed-document-session = { workspace = true }
bed-workbench-api = { workspace = true, features = ["gpu"] }
dear-imgui-rs = { workspace = true }
serde_json = { workspace = true }
rodio = { workspace = true }
gltf = { workspace = true }
bevy = { version = "=0.19.1", default-features = false, features = ["std", "async_executor", "multi_threaded", "reflect_auto_register", "bevy_asset", "bevy_render", "bevy_core_pipeline", "bevy_pbr", "bevy_log", "png"] }

[dev-dependencies]
image = { workspace = true }
